services:
  - type: web
    name: telegram-hello-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: 8234337661:AAHF2YQWwpnmZ6pvoaaEoRYgTlahGOBTafM
